from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    GenreViewSet,
    ComicViewSet,
    OrderViewSet,
    ReviewViewSet,
    WishlistViewSet,
    PromotionViewSet,
    RecommendationViewSet,
)

app_name = "storeDesk"

router = DefaultRouter()
router.register(r"genres", GenreViewSet)
router.register(r"comics", ComicViewSet)
router.register(r"orders", OrderViewSet)
router.register(r"reviews", ReviewViewSet)
router.register(r"wishlist", WishlistViewSet)
router.register(r"promotions", PromotionViewSet)
router.register(r"recommendations", RecommendationViewSet, basename="recommendations")

urlpatterns = [
    path("", include(router.urls)),
]

# Endpoints of interest (auto-generated by router):
# - POST /orders/quote/            -> OrderViewSet.quote (price quote, no mutation)
# - GET  /comics/{id}/share_link/  -> ComicViewSet.share_link
# - GET  /comics/{id}/reviews/     -> ComicViewSet.reviews