# Generated by Django 5.2.4 on 2025-08-30 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsDesk', '0002_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('play', 'Google Play')], default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase_token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['purchase_token'], name='paymentsDes_purchas_5f2ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='paymentsDes_provide_36eef2_idx'),
        ),
    ]
