# Generated by Django 5.2.4 on 2025-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('digital', 'Digital'), ('motion', 'Motion')], max_length=20)),
                ('filter_name', models.CharField(max_length=100)),
            ],
        ),
    ]
