# Generated by Django 5.2.4 on 2025-07-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorDesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
