# Generated by Django 5.2.4 on 2025-07-18 08:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorDesk', '0002_alter_submissions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
