# Generated by Django 5.2.4 on 2025-12-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorDesk', '0003_alter_submissions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcomics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
