# Generated by Django 5.2.4 on 2025-08-19 16:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restocknotification',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='restocknotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeDesk.comic'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed')], default='percentage', max_length=16),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='per_user_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeDesk.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeDesk.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
        migrations.DeleteModel(
            name='RestockNotification',
        ),
    ]
