# Generated by Django 5.2.4 on 2025-08-30 07:48
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDesk', '0010_address_customuser_profiledesk_email_d00d48_idx_and_more'),
        ('storeDesk', '0003_orderitem_alter_comic_options_alter_genre_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # NOTE: Old renames for payment_* removed (source cols may not exist).
        # Add gateway_* normally (MySQL IF NOT EXISTS unsupported on your version).
        migrations.AddField(
            model_name='order',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),

        # You accepted buyer_name -> ship_line1 earlier; keep it and backfill ship_name below.
        migrations.RenameField(
            model_name='order',
            old_name='buyer_name',
            new_name='ship_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mobile',
            new_name='ship_mobile',
        ),

        # Remove old fields
        migrations.RemoveField(model_name='order', name='email'),
        migrations.RemoveField(model_name='order', name='payment_gateway'),
        migrations.RemoveField(model_name='order', name='payment_order_id'),
        migrations.RemoveField(model_name='order', name='pin_code'),

        # Add new fields
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('shipped', 'Shipped'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled'),
                ],
                db_index=True,
                default='pending',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway',
            field=models.CharField(
                choices=[('razorpay', 'Razorpay'), ('none', 'None')],
                db_index=True,
                default='none',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_order_id',
            field=models.CharField(
                blank=True,
                help_text='Gateway Order ID (e.g., Razorpay order_id).',
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_city',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ship_country',
            field=models.CharField(default='India', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ship_pincode',
            field=models.CharField(default='000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ship_state',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Shipping charges applied to the order.',
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Tax (e.g., GST) applied to the order.',
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # DATA FIX: old text in address -> NULL before changing to FK
        migrations.RunSQL(
            sql="UPDATE storedesk_order SET address = NULL WHERE address IS NOT NULL AND address <> '';",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Alter address to FK
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='orders',
                to='profileDesk.address',
            ),
        ),

        # DATA FIX: backfill ship_name from ship_line1 if empty
        migrations.RunSQL(
            sql="""
                UPDATE storedesk_order
                SET ship_name = ship_line1
                WHERE (ship_name IS NULL OR ship_name = '')
                  AND ship_line1 IS NOT NULL AND ship_line1 <> '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Other alters
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Amount expected to be paid via gateway for this order (should equal final_price).',
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Grand total after discounts, shipping, and taxes.',
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('paid', 'Paid'),
                    ('failed', 'Failed'),
                    ('refunded', 'Refunded'),
                    ('cancelled', 'Cancelled'),
                ],
                db_index=True,
                default='pending',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='store_orders',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # Indexes & constraints
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fulfillment_status'], name='storeDesk_o_fulfill_43fe4c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['gateway'], name='storeDesk_o_gateway_e27be7_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(
                condition=models.Q(('shipping_fee__gte', 0)),
                name='order_shipping_fee_gte_0',
            ),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(
                condition=models.Q(('tax_amount__gte', 0)),
                name='order_tax_amount_gte_0',
            ),
        ),
    ]