# Generated by Django 5.2.4 on 2025-12-25 08:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDesk', '0004_rename_payment_payment_id_order_gateway_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_signature',
        ),
        migrations.AlterField(
            model_name='comic',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Average rating between 0.0 and 5.0', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
        migrations.AlterField(
            model_name='comic',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings contributing to average'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gateway_payment_id',
            field=models.CharField(blank=True, help_text='Gateway Payment ID (e.g., Razorpay payment_id).', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='gateway_signature',
            field=models.CharField(blank=True, help_text='Gateway signature (e.g., Razorpay signature).', max_length=256, null=True),
        ),
    ]
