# Generated by Django 5.2.4 on 2025-07-07 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='motioncomics/covers/')),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('view_count', models.IntegerField(default=0)),
                ('favourite_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='motioncomics/episodes/')),
                ('video_url', models.URLField()),
                ('is_free', models.BooleanField(default=False)),
                ('coin_cost', models.IntegerField(default=50)),
                ('is_locked', models.BooleanField(default=True)),
                ('short_description', models.TextField(max_length=200)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motioncomicDesk.comicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=256)),
                ('likes_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_comments', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motioncomicDesk.episodemodel')),
            ],
        ),
    ]
