# Generated by Django 5.2.4 on 2025-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motioncomicDesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicmodel',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
