# Generated by Django 5.2.4 on 2025-07-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motioncomicDesk', '0002_comicmodel_rating_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episodemodel',
            unique_together={('comic', 'episode_number')},
        ),
    ]
