# Generated by Django 5.2.4 on 2025-08-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motioncomicDesk', '0003_alter_episodemodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodemodel',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video for this episode (optional)', null=True, upload_to='motioncomics/episodes/'),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
