# Generated by Django 5.2.4 on 2025-10-08 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motioncomicDesk', '0005_userepisodeunlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicRatingModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('rated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motion Comic Rating',
                'verbose_name_plural': 'Motion Comic Ratings',
            },
        ),
        migrations.CreateModel(
            name='EpisodeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('COINS', 'Coins'), ('PREMIUM', 'Premium'), ('GRANT', 'Grant')], default='COINS', max_length=16)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userepisodeunlock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userepisodeunlock',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='userepisodeunlock',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='episodemodel',
            options={'ordering': ['episode_number']},
        ),
        migrations.AddField(
            model_name='comicmodel',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='episodemodel',
            index=models.Index(fields=['comic', 'episode_number'], name='motioncomic_comic_i_27ec4b_idx'),
        ),
        migrations.AddField(
            model_name='comicratingmodel',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='motioncomicDesk.comicmodel'),
        ),
        migrations.AddField(
            model_name='comicratingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_comic_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episodeaccess',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='motioncomicDesk.episodemodel'),
        ),
        migrations.AddField(
            model_name='episodeaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_episode_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserEpisodeUnlock',
        ),
        migrations.AddIndex(
            model_name='comicratingmodel',
            index=models.Index(fields=['comic'], name='motioncomic_comic_i_eb7b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='comicratingmodel',
            index=models.Index(fields=['user', 'comic'], name='motioncomic_user_id_10eed8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comicratingmodel',
            unique_together={('user', 'comic')},
        ),
        migrations.AddIndex(
            model_name='episodeaccess',
            index=models.Index(fields=['user', 'episode'], name='motioncomic_user_id_cd308f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episodeaccess',
            unique_together={('user', 'episode')},
        ),
    ]
