# Generated by Django 5.2.4 on 2025-08-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carouselDesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitemmodel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='carouselitemmodel',
            name='target_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='carouselitemmodel',
            index=models.Index(fields=['type', 'order'], name='carouselDes_type_dd4d58_idx'),
        ),
        migrations.AddConstraint(
            model_name='carouselitemmodel',
            constraint=models.UniqueConstraint(fields=('type', 'order'), name='uniq_carousel_type_order'),
        ),
    ]
