# Generated by Django 5.2.4 on 2025-09-28 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favouriteDesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritemodel',
            name='comic_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='favouritemodel',
            index=models.Index(fields=['user', 'comic_type', 'comic_id'], name='favouriteDe_user_id_a41842_idx'),
        ),
        migrations.AddIndex(
            model_name='favouritemodel',
            index=models.Index(fields=['comic_type', 'comic_id'], name='favouriteDe_comic_t_5fb4f7_idx'),
        ),
    ]
