# Generated by Django 5.2.4 on 2025-08-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiumDesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='plan',
            field=models.CharField(choices=[('3_month', '3-Month'), ('6_month', '6-Month'), ('12_month', '12-Month')], max_length=50),
        ),
    ]
