# Generated by Django 5.2.4 on 2025-08-16 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiumDesk', '0002_alter_subscriptionmodel_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscriptionmodel',
            index=models.Index(fields=['user', 'end_date'], name='premiumDesk_user_id_2b9409_idx'),
        ),
    ]
