# Generated by Django 5.2.4 on 2025-08-30 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiumDesk', '0003_subscriptionmodel_premiumdesk_user_id_2b9409_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(choices=[('unlock_episode', 'Unlock Episode'), ('admin_adjust', 'Admin Adjust'), ('play_credit', 'Play Credit'), ('refund', 'Refund'), ('other', 'Other')], default='other', max_length=32)),
                ('link_model', models.CharField(blank=True, max_length=64, null=True)),
                ('link_id', models.CharField(blank=True, max_length=64, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='premiumDesk_user_id_a94f74_idx'), models.Index(fields=['idempotency_key'], name='premiumDesk_idempot_f7e38c_idx')],
            },
        ),
    ]
