# Generated by Django 5.2.3 on 2025-07-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='PRTL79cd3c', max_length=20, unique=True),
        ),
    ]
