# Generated by Django 5.2.3 on 2025-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDesk', '0005_alter_customuser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='PRTL86dc8a', max_length=20, unique=True),
        ),
    ]
