# Generated by Django 5.2.3 on 2025-07-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDesk', '0008_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badge',
            field=models.CharField(choices=[('Copper', 'Copper'), ('Gold', 'Gold')], default='Copper', max_length=50),
        ),
    ]
