# Generated by Django 5.2.4 on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDesk', '0010_address_customuser_profiledesk_email_d00d48_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
