# Generated by Django 5.2.4 on 2025-12-25 08:14

import digitalcomicDesk.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='digitalcomics/covers/')),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('view_count', models.IntegerField(default=0)),
                ('favourite_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_creator_comic', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Digital Comic',
                'verbose_name_plural': 'Digital Comics',
                'indexes': [models.Index(fields=['genre'], name='digitalcomi_genre_1693b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='digitalcomics/episodes/')),
                ('content_url', models.URLField(blank=True, null=True)),
                ('content_file', models.FileField(blank=True, help_text='Upload PDF file for this episode (optional)', null=True, upload_to='digitalcomics/episodes/')),
                ('is_free', models.BooleanField(default=False)),
                ('coin_cost', models.IntegerField(default=50)),
                ('is_locked', models.BooleanField(default=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='digitalcomicDesk.comicmodel')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['episode_number'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('coins', 'Coins'), ('premium', 'Premium')], max_length=16)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_episode_access', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='digitalcomicDesk.episodemodel')),
            ],
            options={
                'verbose_name': 'Episode Access',
                'verbose_name_plural': 'Episode Access',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(max_length=256)),
                ('likes_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies (null for top-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='digitalcomicDesk.commentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_comments', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='digitalcomicDesk.episodemodel')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SliceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='1-based sequential order within the episode')),
                ('file', models.ImageField(upload_to=digitalcomicDesk.models.slice_upload_path)),
                ('width', models.PositiveIntegerField(default=1080, help_text='Pixel width, e.g., 1080')),
                ('height', models.PositiveIntegerField(blank=True, help_text='Pixel height if known', null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='digitalcomicDesk.episodemodel')),
            ],
            options={
                'verbose_name': 'Slice',
                'verbose_name_plural': 'Slices',
                'ordering': ['episode', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ComicRatingModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('rated_at', models.DateTimeField(auto_now=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='digitalcomicDesk.comicmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_comic_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comic Rating',
                'verbose_name_plural': 'Comic Ratings',
                'indexes': [models.Index(fields=['comic'], name='digitalcomi_comic_i_1c932f_idx'), models.Index(fields=['user', 'comic'], name='digitalcomi_user_id_1aa874_idx')],
                'unique_together': {('user', 'comic')},
            },
        ),
        migrations.AddIndex(
            model_name='episodemodel',
            index=models.Index(fields=['comic', 'episode_number'], name='digitalcomi_comic_i_fa68be_idx'),
        ),
        migrations.AddIndex(
            model_name='episodemodel',
            index=models.Index(fields=['is_locked'], name='digitalcomi_is_lock_99f413_idx'),
        ),
        migrations.AddIndex(
            model_name='episodemodel',
            index=models.Index(fields=['is_free'], name='digitalcomi_is_free_eda1d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episodemodel',
            unique_together={('comic', 'episode_number')},
        ),
        migrations.AddIndex(
            model_name='episodeaccess',
            index=models.Index(fields=['user', 'episode'], name='digitalcomi_user_id_21a44b_idx'),
        ),
        migrations.AddIndex(
            model_name='episodeaccess',
            index=models.Index(fields=['episode'], name='digitalcomi_episode_3e10d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episodeaccess',
            unique_together={('user', 'episode')},
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=models.Index(fields=['episode'], name='digitalcomi_episode_8f18f0_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=models.Index(fields=['user'], name='digitalcomi_user_id_5af933_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=models.Index(fields=['parent'], name='digitalcomi_parent__265b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='slicemodel',
            index=models.Index(fields=['episode', 'order'], name='digitalcomi_episode_c6ed44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slicemodel',
            unique_together={('episode', 'order')},
        ),
    ]
