# Generated by Django 5.2.4 on 2025-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcomicDesk', '0003_alter_episodemodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicmodel',
            name='is_creator_comic',
            field=models.BooleanField(default=False),
        ),
    ]
