# Generated by Django 5.2.4 on 2025-07-10 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcomicDesk', '0004_comicmodel_is_creator_comic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
