# Generated by Django 5.2.4 on 2025-08-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcomicDesk', '0005_alter_comicmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodemodel',
            name='content_file',
            field=models.FileField(blank=True, help_text='Upload PDF file for this episode (optional)', null=True, upload_to='digitalcomics/episodes/'),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='content_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
