# Generated by Django 5.2.4 on 2025-10-06 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcomicDesk', '0007_episodeaccess_slicemodel_alter_comicmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicRatingModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('rated_at', models.DateTimeField(auto_now=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='digitalcomicDesk.comicmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_comic_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comic Rating',
                'verbose_name_plural': 'Comic Ratings',
                'indexes': [models.Index(fields=['comic'], name='digitalcomi_comic_i_1c932f_idx'), models.Index(fields=['user', 'comic'], name='digitalcomi_user_id_1aa874_idx')],
                'unique_together': {('user', 'comic')},
            },
        ),
    ]
