# Generated by Django 5.2.4 on 2025-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcomicDesk', '0008_comicratingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicmodel',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
