# Generated by Django 5.2.4 on 2025-10-09 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationDesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='collapse_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='comic_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='comic_type',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('motion', 'Motion')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='deeplink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='episode_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='notification_type',
            field=models.CharField(choices=[('digital_launch', 'Digital Comic Launch'), ('digital_episode', 'Digital Comic Episode'), ('motion_launch', 'Motion Comic Launch'), ('motion_episode', 'Motion Comic Episode'), ('admin', 'Admin Broadcast')], default='admin', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='ttl',
            field=models.PositiveIntegerField(default=172800),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='related_tab',
            field=models.CharField(choices=[('home', 'Home'), ('community', 'Community'), ('store', 'Store')], default='home', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['user', 'read_at', '-created_at'], name='notificatio_user_id_52c4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_83efc3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['comic_type', 'comic_id'], name='notificatio_comic_t_6f57a9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['related_tab', '-created_at'], name='notificatio_related_9a57c0_idx'),
        ),
    ]
