# Generated by Django 5.2.4 on 2025-10-01 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('digital', 'Digital'), ('motion', 'Motion')], max_length=16)),
                ('comic_id', models.IntegerField()),
                ('episode_id', models.IntegerField(blank=True, null=True)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('position_ms', models.IntegerField(blank=True, null=True)),
                ('comic_title', models.CharField(blank=True, default='', max_length=255)),
                ('episode_label', models.CharField(blank=True, default='', max_length=255)),
                ('cover_url', models.URLField(blank=True, default='')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-last_read_at'], name='readingActi_user_id_6aeb95_idx'), models.Index(fields=['user', '-finished_at'], name='readingActi_user_id_0dbab6_idx'), models.Index(fields=['user', 'type', 'comic_id'], name='readingActi_user_id_44926e_idx')],
                'unique_together': {('user', 'type', 'comic_id')},
            },
        ),
    ]
