# Generated by Django 5.2.4 on 2025-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingActivityDesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingactivity',
            name='comic_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='readingactivity',
            name='episode_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
