# Generated by Django 5.2.4 on 2025-09-27 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityDesk', '0002_comment_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEngagementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_read_count', models.PositiveIntegerField(default=0)),
                ('motion_watch_count', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Engagement Stats',
                'verbose_name_plural': 'User Engagement Stats',
            },
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'following'], name='communityDe_followe_9ddb33_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='communityDe_followi_183f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='communityDe_followe_ff71af_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'user'], name='communityDe_post_id_d997b4_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user'], name='communityDe_user_id_a7a8eb_idx'),
        ),
        migrations.AddField(
            model_name='userengagementstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userengagementstats',
            index=models.Index(fields=['user'], name='communityDe_user_id_87c59c_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementstats',
            index=models.Index(fields=['streak_days'], name='communityDe_streak__4c4fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementstats',
            index=models.Index(fields=['comic_read_count'], name='communityDe_comic_r_8f014f_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementstats',
            index=models.Index(fields=['motion_watch_count'], name='communityDe_motion__6c914a_idx'),
        ),
    ]
